name: CMake

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - uses: lukka/get-cmake@latest

    - name: Restore artifacts, or setup vcpkg (do not install any package)
      uses: lukka/run-vcpkg@v10
      with:
        vcpkgGitCommitId: "1a5075baf8e5a1a10fab6282c18587741dcc155e"

    - name: Run CMake to install the dependencies specified in the vcpkg.json manifest, generate project file and build the project
      uses: lukka/run-cmake@v10
      with:
         configurePreset: 'windows-release'
         buildPreset: 'ninja-multi-vcpkg'
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ogls-${{ github.sha }}
        path: ${{ runner.workspace }}/build/*
        
