name: CMake

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - uses: lukka/get-cmake@latest

    - name: Restore artifacts, or setup vcpkg (do not install any package)
      uses: lukka/run-vcpkg@v6
      with:      
        setupOnly: true
        appendedCacheKey: ${{ hashFiles( '**/vcpkg.json' ) }}
        vcpkgTriplet: "x64-windows"
        additionalCachedPaths: ${{ env.buildDir }}/vcpkg_installed
        vcpkgGitCommitId: "3166bcc15b156b57667d9e573fba9775ceef3eb1"

    - name: Run CMake to install the dependencies specified in the vcpkg.json manifest, generate project file and build the project
      uses: lukka/run-cmake@v3
      with:
        useVcpkgToolchainFile: true
        buildDirectory: ${{ runner.workspace }}/build
        cmakeBuildType: "Release"
        cmakeAppendedArgs: '-GNinja'
        
