name: CMake

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - uses: lukka/get-cmake@latest

    - name: Restore artifacts, or setup vcpkg (do not install any package)
      uses: lukka/run-vcpkg@v10
      with:
        vcpkgGitCommitId: "1a5075baf8e5a1a10fab6282c18587741dcc155e"

#   - name: List $RUNNER_WORKSPACE before build
#     run: find $RUNNER_WORKSPACE
#     shell: bash
        
    - name: Run CMake to install the dependencies specified in the vcpkg.json manifest, generate project file and build the project
      uses: lukka/run-cmake@v10
      with:
         configurePreset: 'windows-release'
         buildPreset: 'windows-release'
         
#   - name: List $RUNNER_WORKSPACE after build
#     run: find $RUNNER_WORKSPACE
#     shell: bash
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ogls-${{ github.sha }}
        path: ${{ runner.workspace }}/opengl-starter/out/build/windows-release/opengl_starter/*
       
    - name: Create a Release
      uses: elgohr/Github-Release-Action@master
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        args: Build ${{ steps.vars.outputs.sha_short }}
